name: Test and Build

on:
  pull_request:
    branches:
        - dev
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Test with Maven
      run: |
        cd backend/pinklifeline
        mvn test

  build_deploy:
      runs-on: ubuntu-latest
      needs: test
  
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Move to backend directory
        run: cd backend/pinklifeline
      - name: Get Version Name
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"
      - name: Build Docker image
        run: docker build -t sadatul/pinklifeline_dev:${{ steps.version.outputs.VERSION }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Images to Docker Hub
        run: docker push sadatul/pinklifeline_dev:${{ steps.version.outputs.VERSION }}

      