name: Production Build and Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Print Version Name
        run: echo ${{ github.ref_name }}
      - name: Build Docker image
        run: docker build --build-arg profile=prod -t sadatul/pinklifeline_prod:${{github.ref_name}} -t sadatul/pinklifeline_prod:latest ./backend/pinklifeline
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Images to Docker Hub
        run: |
         docker push sadatul/pinklifeline_prod:${{github.ref_name}}
         docker push sadatul/pinklifeline_prod:latest